# -*- coding: utf-8 -*-
"""kakeibo10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzLe9SnNaqP_OJcWsTz9ocgAeItG-Nip
"""

import csv

# 1) 基本情報
wage = int(input("基本時給はいくらですか？: "))
days = int(input("今月は何日ありますか？（28/30/31）: "))

income_by_day = [0.0] * days

# 2) 勤務日をまとめて入力
raw = input("働いた日付をカンマ区切りで入力（例: 10,15,22 / なしならEnter）: ").strip()
if raw == "":
    work_days = []
else:
    work_days = []
    for token in raw.split(","):
        token = token.strip()
        if token == "":
            continue
        try:
            d = int(token)
        except ValueError:
            print(f"無効: {token}（数字ではありません）")
            continue
        if 1 <= d <= days:
            work_days.append(d)
        else:
            print(f"無効: {d}（1〜{days}の範囲外）")

# 重複を消す（入力順を保つ）
seen = set()
work_days_unique = []
for d in work_days:
    if d not in seen:
        seen.add(d)
        work_days_unique.append(d)
work_days = work_days_unique

print("勤務日:", work_days)

# 3) 勤務日のみ詳細入力
for day in work_days:
    print(f"\n--- {day}日 ---")

    time_str = input("日中の勤務時間（例 1:45）: ")
    try:
      h,m=time_str.split(":")
      hour=int(h)+int(m)/60
    except:
      print("入力形式は1:45のように入力してください")
      continue
    late_str=input("22時以降の勤務時間(例 0:30):")

    try:
      lh,lm=late_str.split(":")
      late=int(lh)+int(lm)/60
    except:
      print("入力形式は0:30のように入力してください")
      continue

    if not(0<=int(m)<60):
      print("分は0~59で入力してください")
      continue

    income = wage * hour  + wage * 1.25 * late
    income_by_day[day - 1] = income
    print(f"{day}日の収入: {int(income)} 円")

# 4) 集計（平均は出さない）
total_income = sum(income_by_day)
work_income = [x for x in income_by_day if x > 0]

print("\n【月レポート】")
print(f"収入合計: {int(total_income)} 円")

if work_income:
    max_income = max(work_income)
    min_income = min(work_income)

    max_days = [i + 1 for i, x in enumerate(income_by_day) if x == max_income]
    min_days = [i + 1 for i, x in enumerate(income_by_day) if x == min_income]

    print(f"最高収入: {int(max_income)} 円（{max_days}日）")
    print(f"最低収入: {int(min_income)} 円（{min_days}日）")
else:
    print("稼働日がありませんでした（最高/最低は算出なし）")

# 5) CSV出力（成果物）
with open("monthly_income_report.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["日付", "収入(円)"])
    for i in range(days):
        writer.writerow([i + 1, int(income_by_day[i])])

    writer.writerow([])
    writer.writerow(["収入合計", int(total_income)])
    if work_income:
        writer.writerow(["最高収入", int(max_income)])
        writer.writerow(["最高収入の日", str(max_days)])
        writer.writerow(["最低収入", int(min_income)])
        writer.writerow(["最低収入の日", str(min_days)])
    else:
        writer.writerow(["最高収入", "N/A"])
        writer.writerow(["最低収入", "N/A"])

baito-income-tool/
  main.py
  README.md
  sample_output.csv